const now = new Date();

export const DEMO_NEGOCIO_ID = "00000000-0000-0000-0000-000000000010";
export const DEMO_EMPLEADO_USUARIO_ID = "00000000-0000-0000-0000-000000000002";

export const mockNegocios = [
  {
    id: DEMO_NEGOCIO_ID,
    nombre: "Smart Style",
    slug: "smart-style",
    telefono: "3503803010",
    correo: "smartstyle@barberlab.local",
    direccion: "Cra 15 # 82-30, Bogotá",
    representante: "Admin Smart Style",
    tipoDocumento: "nit",
    numeroDocumento: "901234567",
    ciudadIndicativo: "601",
    contactoPrincipal: "3503803010",
    descripcion: "CRM demo para validar agenda, turnos, inventario y reportes.",
    slogan: "Controla agenda, caja y rentabilidad con una operación clara.",
    logoUrl: null,
    colorPrimario: "#111827",
    colorSecundario: "#22d3ee",
    colorAcento: "#7c3aed",
    fuente: "Inter",
    configVisual: {},
    settings: {},
    plan: "pro",
    estado: "activo",
    modoAislamiento: "multi_tenant",
    comisionBase: "precio_final",
    propinaEnComision: false,
    fechaInicio: "2026-01-15",
    fechaFin: "2026-08-15",
    createdAt: now,
    updatedAt: now,
    adminEmail: "admin@operux.local",
  },
  {
    id: "00000000-0000-0000-0000-000000000011",
    nombre: "Barber King",
    slug: "barber-king",
    telefono: "3015551122",
    correo: "contacto@barberking.co",
    direccion: "Cll 45 # 12-08, Medellín",
    representante: "Julián King",
    tipoDocumento: "cc",
    numeroDocumento: "1020304050",
    ciudadIndicativo: "604",
    contactoPrincipal: "3015551122",
    descripcion: "Barbería clásica con 4 sillas.",
    slogan: "El corte que manda.",
    logoUrl: null,
    colorPrimario: "#111827",
    colorSecundario: "#f59e0b",
    colorAcento: "#dc2626",
    fuente: "Inter",
    configVisual: {},
    settings: {},
    plan: "starter",
    estado: "suspendido",
    modoAislamiento: "multi_tenant",
    comisionBase: "precio_final",
    propinaEnComision: false,
    fechaInicio: "2026-02-01",
    fechaFin: "2026-07-01",
    createdAt: now,
    updatedAt: now,
    adminEmail: "julian@barberking.co",
  },
];

export const mockNegocioUsers = [
  {
    id: "00000000-0000-0000-0000-000000000001",
    nombre: "Admin Smart Style",
    email: "admin@operux.local",
    rol: "admin" as const,
    telefono: "3503803010",
    activo: true,
    createdAt: now,
  },
  {
    id: DEMO_EMPLEADO_USUARIO_ID,
    nombre: "Mateo Barber",
    email: "empleado@operux.local",
    rol: "empleado" as const,
    telefono: "3101112233",
    activo: true,
    createdAt: now,
  },
];

export const mockEmpleado = {
  id: "00000000-0000-0000-0000-000000000020",
  negocioId: DEMO_NEGOCIO_ID,
  usuarioId: DEMO_EMPLEADO_USUARIO_ID,
  especialidad: "barberia" as const,
  comisionPct: "40",
  activo: true,
  createdAt: now,
  updatedAt: now,
};

export const mockEmpleadoCitas = [
  {
    id: "cita-1",
    inicio: new Date(now.getTime() + 30 * 60000),
    fin: new Date(now.getTime() + 75 * 60000),
    estado: "confirmada" as const,
    cliente: "Paula Gomez",
    telefono: "3001234567",
    servicio: "Corte y barba",
    precio: "65000",
    duracionMin: 45,
  },
  {
    id: "cita-2",
    inicio: new Date(now.getTime() + 120 * 60000),
    fin: new Date(now.getTime() + 165 * 60000),
    estado: "reservada" as const,
    cliente: "Daniel Ruiz",
    telefono: "3019876543",
    servicio: "Corte premium",
    precio: "45000",
    duracionMin: 45,
  },
];

export const mockTurnos = [
  {
    id: "turno-1",
    createdAt: now,
    precioFinal: "45000",
    propina: "5000",
    metodoPago: "transferencia" as const,
    cliente: "Carlos Rojas",
    servicio: "Corte premium",
    empleado: "Mateo Barber",
  },
  {
    id: "turno-2",
    createdAt: now,
    precioFinal: "80000",
    propina: "0",
    metodoPago: "tarjeta" as const,
    cliente: "Laura Vega",
    servicio: "Manicure semipermanente",
    empleado: "Sofia Nails",
  },
  {
    id: "turno-3",
    createdAt: now,
    precioFinal: "120000",
    propina: "10000",
    metodoPago: "efectivo" as const,
    cliente: "Andres Mora",
    servicio: "Tatuaje pequeno",
    empleado: "Nico Ink",
  },
];

export const mockCitas = [
  {
    id: "cita-1",
    inicio: now,
    estado: "confirmada" as const,
    cliente: "Paula Gomez",
    servicio: "Corte y barba",
    precio: "65000",
    empleado: "Mateo Barber",
  },
  {
    id: "cita-2",
    inicio: new Date(now.getTime() + 3600000),
    estado: "reservada" as const,
    cliente: "Daniel Ruiz",
    servicio: "Spa de unas",
    precio: "90000",
    empleado: "Sofia Nails",
  },
];

export const mockGastos = [
  {
    id: "gasto-1",
    categoria: "arriendo" as const,
    monto: "1800000",
    fecha: "2026-05-28",
    descripcion: "Arriendo local",
    comprobanteUrl: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "gasto-2",
    categoria: "insumos" as const,
    monto: "420000",
    fecha: "2026-05-27",
    descripcion: "Reposicion de cuchillas, gel y tintas",
    comprobanteUrl: null,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockDepositos = [
  {
    id: "dep-1",
    citaId: "cita-tat-1",
    clienteId: "cli-1",
    monto: "80000",
    metodoPago: "transferencia" as const,
    estado: "recibido" as const,
    notas: "Anticipo manga completa",
    comprobanteUrl: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "dep-2",
    citaId: "cita-tat-2",
    clienteId: "cli-2",
    monto: "50000",
    metodoPago: "efectivo" as const,
    estado: "aplicado" as const,
    notas: "Depósito tatuaje espalda",
    comprobanteUrl: null,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockClienteArchivos = [
  {
    id: "arch-1",
    clienteId: "cli-1",
    citaId: "cita-tat-1",
    tipo: "boceto" as const,
    url: "https://placehold.co/400x400/1a1a2e/7F77DD?text=Boceto+1",
    storagePath: null,
    nombre: "Boceto manga dragón",
    descripcion: "Primera propuesta de manga con dragón japonés",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "arch-2",
    clienteId: "cli-1",
    citaId: null,
    tipo: "referencia" as const,
    url: "https://placehold.co/400x400/1a1a2e/F5C400?text=Ref+Cliente",
    storagePath: null,
    nombre: "Referencia cliente",
    descripcion: "Imagen de referencia traída por el cliente",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "arch-3",
    clienteId: "cli-1",
    citaId: "cita-tat-2",
    tipo: "resultado" as const,
    url: "https://placehold.co/400x400/1a1a2e/27C3D8?text=Resultado",
    storagePath: null,
    nombre: "Resultado sesión 1",
    descripcion: "Foto finalizada de la primera sesión",
    createdAt: now,
    updatedAt: now,
  },
];

export const mockInventario = [
  {
    id: "inv-1",
    sku: "BAR-001",
    nombre: "Cuchilla premium",
    categoria: "barberia",
    unidad: "unidad",
    stock: "36",
    costoUnitario: "1800",
    stockMinimo: "20",
    precioVenta: "12000",
    visibleCliente: true,
    descripcion: "Cuchilla premium para acabados limpios y seguros.",
    fotoUrl: null,
    activo: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "inv-2",
    sku: "NAI-010",
    nombre: "Gel semipermanente",
    categoria: "unas",
    unidad: "ml",
    stock: "8",
    costoUnitario: "9000",
    stockMinimo: "10",
    precioVenta: "32000",
    visibleCliente: true,
    descripcion: "Gel para spa de uñas con acabado profesional.",
    fotoUrl: null,
    activo: true,
    createdAt: now,
    updatedAt: now,
  },
];
